name = "Create Vibrantly [Forge]"
author = "actually_aenzo"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "30f412aad5beab920bb8f5863c740e7bf8b7fc5502a3a6c1924bbfa4c40d07b4"

[versions]
forge = "43.1.52"
minecraft = "1.19.2"
