name = "Create Vibrantly [Forge]"
author = "actually_aenzo"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2d44d196bb243f543c7d14e3c4a46332c2164f12511eafc7b97150474c929b5"

[versions]
forge = "43.1.52"
minecraft = "1.19.2"
