name = "Create Vibrantly [Forge]"
author = "actually_aenzo"
version = "2.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e06e0fc6964de1a4f8b8b257bff3d3bc074bae31c85f3568940185913d9088b0"

[versions]
forge = "43.1.52"
minecraft = "1.19.2"
