name = "Create Vibrantly [Forge]"
author = "actually_aenzo"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "206c83c022736941dd2c902ca08dfdc2175eb93c8567ac3ef69536b33256ba84"

[versions]
forge = "43.1.52"
minecraft = "1.19.2"
