name = "Create Vibrantly [Forge]"
author = "actually_aenzo"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2d3af7225da54b8b7951934f147ce7b79fdd9d5a61f35d42bbc31c8dc8186910"

[versions]
forge = "43.1.52"
minecraft = "1.19.2"
