name = "Create Vibrantly [Forge]"
author = "actually_aenzo"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1a6540a095168c74ff66e376aaa0f3af7e5d95eeb44b6b07e3d36642191b1b54"

[versions]
forge = "43.1.52"
minecraft = "1.19.2"
