name = "Create Vibrantly [Forge]"
author = "actually_aenzo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c33aa7ebbad8960e6ee70c482e17e1755340426c24765f742db4d3790251b673"

[versions]
forge = "43.1.52"
minecraft = "1.19.2"
