name = "Create Vibrantly [Forge]"
author = "actually_aenzo"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d6b5d652708f62cb5c47b2ee694880af6402b744e4b8f53a41c6b689a8662a5e"

[versions]
forge = "43.1.52"
minecraft = "1.19.2"
