name = "Create Vibrantly [Forge]"
author = "actually_aenzo"
version = "0.1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "100d874c60ac88cb81c7641f7d62439e21d82e3adb7047447fb57b8dd3279435"

[versions]
forge = "43.1.52"
minecraft = "1.19.2"
