name = "Create Vibrantly [Forge]"
author = "actually_aenzo"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b1b6b7cfa09c578332a58c44853eab5102d791fbd287656300eb26fc4a59de06"

[versions]
forge = "43.1.52"
minecraft = "1.19.2"
