name = "Create Vibrantly [Forge]"
author = "actually_aenzo"
version = "0.1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "845f51ff7fec44c42540f581d7b57fba7f3ff71eb019bbb67d571424bd00d334"

[versions]
forge = "43.1.52"
minecraft = "1.19.2"
