name = "Create Vibrantly [Forge]"
author = "actually_aenzo"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dab13699a9622e67c83c51883e8fed542f74b056d11d4357f8d34b089282574f"

[versions]
forge = "43.1.52"
minecraft = "1.19.2"
