name = "Create Vibrantly [Forge]"
author = "actually_aenzo"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "14f39be44af8bbc3b67903a9b1d5cd3423487602bc7a2c9bb4b7e2ad93f71ede"

[versions]
forge = "43.1.52"
minecraft = "1.19.2"
